---
kind: pipeline
type: kubernetes
name: linux-amd64

steps:
- name: gotest
  image: golang:1.13
  commands:
  - go test ./...
  environment:
    GITHUB_TOKEN:
      from_secret: github_token

- name: build:webui
  image: node:12
  commands:
  - cd webui
  - yarn install
  - yarn run build

- name: build:go
  image: golang:1.13
  commands:
  - go get github.com/gobuffalo/packr/v2/packr2
  - packr2
  - go build -ldflags "-w -extldflags \"-static\"" -o release/pinmonl-$${GOOS}-$${GOARCH}
  - packr2 clean
  environment:
    GOOS: linux
    GOARCH: amd64

- name: build:docker
  image: plugins/docker
  settings:
    auto_tag: true
    username:
      from_secret: dockerhub_username
    password:
      from_secret: dockerhub_password
    repo: pinmonl/pinmonl
    dockerfile: docker/Dockerfile
    build_args:
    - BUILD_OS=linux
    - BUILD_ARCH=amd64
  when:
    event:
    - push
    - tag

---
kind: secret
name: github_token
get:
  path: pinmonl-secret
  name: github_token

---
kind: secret
name: dockerhub_username
get:
  path: pinmonl-secret
  name: dockerhub_username

---
kind: secret
name: dockerhub_password
get:
  path: pinmonl-secret
  name: dockerhub_password
